apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: WAAS
    app.kubernetes.io/name: WAAS
    waas-prometheus-service: monitor
  name: f5gc-ausf
spec:
  ports:
  - name: http
    port: 29509
    protocol: TCP
    targetPort: 9000
  - name: stats
    port: 8080
    protocol: TCP
    targetPort: 19010
  - name: fb-stats
    port: 2020
    protocol: TCP
    targetPort: 2020
  selector:
    configid: waas-f5gc-ausf-container
  type: ClusterIP
