apiVersion: v1
kind: Service
metadata:
  labels:
    app: f5gc-webui
  name: f5gc-webui
spec:
  type: NodePort
  ports:
  - name: f5gc-webui
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 31500
  selector:
    app: f5gc-webui
