---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: f5gc-upf-n3
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "mtu": 8800,
      "master": "ens224",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": "192.168.10.20/24",
                        "gateway": "192.168.10.1"
                }
        ]
      }
    }'

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: f5gc-upf-n4
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "ens256",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": "172.16.30.30/24",
                        "gateway": "172.16.30.1"
                }
        ]
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: f5gc-upf-n6
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "mtu": 1500,
      "master": "ens161",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": "172.15.10.20/24",
                        "gateway": "172.15.10.1"
                }
        ]
      }
    }'

