apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.app.name }}-postdelete-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "waas.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": "before-hook-creation"
