image:
  registry:
  version:
enabled: true
nodeSelector: {}
tolerations: []
affinity: {}

## settings for specific containers
containers:
  enforcer:
    registry:
    version:
  logrotate:
    registry:
    version:
  fluentbit:
    registry:
    version:
    resources:
      {}