apiVersion: v1
kind: ConfigMap
metadata:
  name: f5gc-pcf-config
data:
  pcfcfg.conf: |
    info:
      version: 1.0.0
      description: PCF initial local configuration

    configuration:
      pcfName: PCF
      sbi:
        scheme: http
        registerIPv4: f5gc-pcf     # Can also be a kubernetes service IP or domain name.
        bindingIPv4: 0.0.0.0      # Can also be an ENV.
        port: 29507
      timeFormat: 2019-01-02 15:04:05
      defaultBdtRefId: BdtPolicyId-
      nrfUri: http://f5gc-nrf:29510
      serviceList:
        - serviceName: npcf-am-policy-control
        - serviceName: npcf-smpolicycontrol
          suppFeat: 3fff
        - serviceName: npcf-bdtpolicycontrol
        - serviceName: npcf-policyauthorization
          suppFeat: 3
        - serviceName: npcf-eventexposure
        - serviceName: npcf-ue-policy-control

  free5GC.conf: |
    db_uri: mongodb://f5gc-mongodb:27017/free5gc

    #all logging levels
    #panic
    #fatal
    #error
    #warn
    #debug
    #debug
    #trace
    logger:
    # network function
      AMF:
        debugLevel: info
        ReportCaller: true
      SMF:
        debugLevel: info
        ReportCaller: true
      UDR:
        debugLevel: info
        ReportCaller: true
      UDM:
        debugLevel: info
        ReportCaller: true
      NRF:
        debugLevel: info
        ReportCaller: true
      PCF:
        debugLevel: info
        ReportCaller: true
      AUSF:
        debugLevel: info
        ReportCaller: true
      N3IWF:
        debugLevel: info
        ReportCaller: true
    # library
      NAS:
        debugLevel: info
        ReportCaller: true
      FSM:
        debugLevel: info
        ReportCaller: true
      NGAP:
        debugLevel: info
        ReportCaller: true
      NamfComm:
        debugLevel: info
        ReportCaller: true
      NamfEventExposure:
        debugLevel: info
        ReportCaller: true
      NsmfPDUSession:
        debugLevel: info
        ReportCaller: true
      NudrDataRepository:
        debugLevel: info
        ReportCaller: true
      OpenApi:
        debugLevel: info
        ReportCaller: true
      Aper:
        debugLevel: info
        ReportCaller: true
      CommonConsumerTest:
        debugLevel: info
        ReportCaller: true
    # webui
      WEBUI:
        debugLevel: info
        ReportCaller: true
