apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.global.app.name }}-preinstall-role-binding
  labels:
    {{- include "waas.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": "before-hook-creation"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.app.name }}-preinstall-service-account
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.global.app.name }}-preinstall-role
  apiGroup: rbac.authorization.k8s.io