---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: f5gc-mongodb
  name: f5gc-mongodb
spec:
  type: NodePort
  ports:
  - name: f5gc-mongodb
    port: 27017
    targetPort: 27017
    protocol: TCP
    nodePort: 31502
  selector:
    app: f5gc-mongodb
